OPENAI_API_KEY="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"
OPENAI_MODEL="gpt-3.5-turbo-0125"
GITHUB_USERNAME="ris2002"

DB_HOST="ep-wild-bar-a5tb04s4.us-east-2.aws.neon.tech"
DB_NAME="billionaire2023g3nai"
DB_USERNAME="g3nai"
DB_PASSWORD="pXwa1DVfB8lk"

LANGCHAIN_TRACING_V2="true"
LANGCHAIN_ENDPOINT="https://api.smith.langchain.com"
LANGCHAIN_API_KEY="ls__9dae7f6c7cba4bcb87355d1d472072c3"
LANGCHAIN_PROJECT="ris2002-billionaire2023"
